### ISSUE TITLE
How do I remove the name tag from the screen?

### ISSUE THREAD

**Issue by SamuraiVXI** [krystalgamer/usm-debug-menu#3]

**Comment by MrUltimateSpiderManMODDER** [comment]
use this version https://github.com/MrUltimateSpiderManMODDER/usm-debug-menu and fork

**Comment by SamuraiVXI** [comment]
Sorry if I'm being stupid, but how do I do that? I can only install the master version, and have no idea what fork means in this context.

**Comment by MrUltimateSpiderManMODDER** [comment]
you know language c or c++
