### ISSUE TITLE
Debug Menu not opening

### ISSUE THREAD

**Issue by OoFridgeRaideroO** [krystalgamer/usm-debug-menu#4]
I'm trying to use the debug menu and the watermark shows up in-game, but pressing INSERT does nothing and the menu won't open.
I checked the log and it says "hooking destroy_debug_menu_entry" Maybe that has something to do with it

**Comment by OoFridgeRaideroO** [comment]
Just read that you need a USB keyboard, as the keybind set doesn't work on laptops. Maybe change the keybind to something that would work on both?

**Comment by OoFridgeRaideroO** [comment]
Fixed the issue by using an on-screen keyboard, as pressing insert doesn't open the menu, if using a laptop

**Comment by UltimateSpider-Man** [comment]
try this https://github.com/MrMartinIden/usm-debug-menu
